version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lesweb
      POSTGRES_DB: TicketsDb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  api:
    build:
      context: ./TicketingSystem
    depends_on:
      - postgres
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Database=TicketsDb;Username=postgres;Password=lesweb
    ports:
      - "5000:8080"

  frontend:
    build:
      context: ./ticketing-frontend
    depends_on:
      - api
    ports:
      - "3000:80"
